language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "nightly"
    - "pypy"

install:
    - pip install pytest pytest-cov
    - pip install -r requirements.txt
    - travis_retry python setup.py install

script:
    - py.test dbThrottle/tests/test_throttle_iter.py

notifications:
  slack: rbirm:fjJKXGPbjyXSGAKKaOU6GWEh
